language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
  - pypy
  - pypy3
jobs:
  include:
    - name: flake8
      install: pip install flake8
      script: flake8 *.py
      after_success:
install:
  - pip install coverage coverage-python-version coveralls
script:
  - coverage run test_profilehooks.py
  - coverage report -m --fail-under=100
after_success:
  - coveralls
notifications:
  email: false
